version = 3.4.3

runner.dialect = scala3

maxColumn = 100

preset = default

docstrings.style = keep

align.preset = more
align.tokens.add = [":"]

trailingCommas = always

continuationIndent {
  callSite = 2
  defnSite = 2
}

rewrite.rules = [
  RedundantBraces, RedundantParens, SortModifiers, prefercurlyfors
]

newlines {
  beforeCurlyLambdaParams = multilineWithCaseOnly
}
