addSbtPlugin("com.github.sbt"   % "sbt-release"            % "1.1.0")
addSbtPlugin("com.evolution"    % "sbt-scalac-opts-plugin" % "0.0.9")
addSbtPlugin("com.evolution"    % "sbt-artifactory-plugin" % "0.0.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"           % "2.4.6")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"            % "0.6.4")
