name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.16
          - 3.3.4

    steps:
      - uses: actions/checkout@v2

      - uses: coursier/cache-action@v6

      - name: scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 17

      - name: build ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean test